### ISSUE TITLE
Останавливать приложение, если не загрузились модели

### ISSUE THREAD

**Issue by PhySci** [Darveivoldavara/ocr_for_medical_certificates#1]
В app.py есть код для подгрузки моделей, там ловятся exceptions, о них выдаются сообщения и идёт дальше. Но по логике в этот момент всё должно падать. Нет смысла запускать приложение, если модели не загрузились. Поэтому в обработке ошибок надо дальше распространять exception. Т.е. добавить строчку raise e

**Comment by Darveivoldavara** [comment]
Исправлено
