### ISSUE TITLE
Сохранённые модели не подгружаются

### ISSUE THREAD

**Issue by PhySci** [Darveivoldavara/ocr_for_medical_certificates#2]
При запуске сервиса и попытке подгрузить модели появляются ошибки

_docker-web-1     | ERROR:root:Error while loading model: invalid load key, 'v'.
docker-worker-1  | ERROR:root:Error while loading model: invalid load key, 'v'.
docker-web-1     | ERROR:root:Error while loading encoder: invalid load key, 'v'.
docker-web-1     | ERROR:root:Error while loading classifier: invalid load key, 'v'.
docker-worker-1  | ERROR:root:Error while loading encoder: invalid load key, 'v'.
docker-worker-1  | ERROR:root:Error while loading classifier: invalid load key, 'v'._

**Comment by Darveivoldavara** [comment]
Причина найдена, необходимо использовать [Git LFS](https://git-lfs.com/) при клонировании репозитория.
Информация добавлена в README проекта.
